name: Update meta tags (trends)

on:
  workflow_dispatch: {}          # запуск вручную из вкладки Actions
  schedule:
    - cron: "17 */6 * * *"       # каждые 6 часов

permissions:
  contents: write                # важно: мы уже включили Read & write в Settings

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pytrends PyGithub

      - name: Update meta tags via script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # встроенный токен
          REPO_NAME: <owner>/<repo>                   # ← замени на свой, например AiCoinETH/getaicoin.com
          HTML_PATH: index.html                       # путь к файлу (если он в корне)
        run: python scripts/update_meta.py