name: Update meta tags

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */3 * *"   # каждые 3 дня в 06:00 UTC

permissions:
  contents: write   # нужно, чтобы обновлять файл через API

jobs:
  update-meta:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: ${{ github.repository }}      # чтобы не писать вручную owner/repo
      HTML_PATH: index.html
      # необязательно: токен X/Twitter API v2, если есть
      X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytrends PyGithub

      - name: Run updater
        run: python scripts/update_meta.py